name: Build and Push Docker image

on:
  push:
    paths:
      - Dockerfile
      - index.html
      - deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t namamu/my-web:latest .
        docker push namamu/my-web:latest

    - name: Update deployment.yaml (optional)
      run: |
        # kalau ingin update tag/commit SHA otomatis
        # atau bisa pakai Kustomize with ArgoCD Image Updater
